//
// AWSConfiguration.h
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.6
//
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:eb30693d-7ac3-4139-8a81-0c5ed24a8dc2"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"35f882704b5d48889e2eec38dd5b2138"
// CONTENT DELIVERY
#define AWS_CONTENT_MANAGER_S3_BUCKET_NAME @"pocketfacilitator-contentdelivery-mobilehub-95915349"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"pocketfacilitator-userfiles-mobilehub-95915349"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub fa20e07d-545e-4a10-b6e3-567159018cec aws-my-sample-app-ios-objc-v0.6"
